packages:
  - packages/*
  - playground

catalogs:
  dev:
    '@ntnyq/eslint-config': ^4.3.0
    '@ntnyq/prettier-config': ^3.0.1
    '@types/node': ^22.16.3
    consola: ^3.4.2
    '@changesets/changelog-github': ^0.5.1
    '@changesets/cli': ^2.29.5
    eslint: ^9.31.0
    husky: ^9.1.7
    nano-staged: ^0.8.0
    npm-run-all2: ^8.0.4
    tinyexec: ^1.0.1
    tsx: ^4.20.3
    prettier: ^3.6.2
    typescript: ^5.8.3
    unbuild: ^3.5.0
  play:
    '@iconify-json/fluent-emoji-flat': ^1.2.3
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/tabler': ^1.2.19
    '@vitejs/plugin-vue': ^5.2.4
    '@vueuse/core': ^13.5.0
    unocss: ^66.3.3
    unplugin-vue-router: ^0.14.0
    vite: ^7.0.4
    vue: ^3.5.17
    vue-router: ^4.5.1
  prod:
    uncase: ^0.1.0
    '@unocss/core': ^66.3.3
  test:
    '@vitest/coverage-v8': ^3.2.4
    vitest: ^3.2.4
overrides:
  esbuild: ^0.25.4

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
