packages:
  - packages/*
  - playground
catalogs:
  dev:
    '@ntnyq/eslint-config': ^4.0.1
    '@ntnyq/prettier-config': ^2.0.0
    '@types/node': ^22.13.10
    consola: ^3.4.0
    '@changesets/changelog-github': ^0.5.1
    '@changesets/cli': ^2.28.1
    eslint: ^9.22.0
    husky: ^9.1.7
    nano-staged: ^0.8.0
    npm-run-all2: ^7.0.2
    tinyexec: ^0.3.2
    tsx: ^4.19.3
    prettier: ^3.5.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
  play:
    '@iconify-json/fluent-emoji-flat': ^1.2.3
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/tabler': ^1.2.17
    '@unocss/reset': ^66.1.0-beta.5
    '@vitejs/plugin-vue': ^5.2.1
    '@vueuse/core': ^13.0.0
    unocss: ^66.1.0-beta.5
    unplugin-vue-router: ^0.12.0
    vite: ^6.2.2
    vue: ^3.5.13
    vue-router: ^4.5.0
  prod:
    uncase: ^0.0.4
    '@unocss/core': ^66.1.0-beta.5
  test:
    '@vitest/coverage-v8': ^3.0.8
    vitest: ^3.0.8
overrides:
  esbuild: ^0.25.1
onlyBuiltDependencies:
  - esbuild
